---
- hosts: vagrant
  user: vagrant
  sudo: yes
  # uncomment for faster provisioning
#  gather_facts: False
  vars:
    - distro_codename: precise

  roles:
    - common
    - deploy-user
    - ruby
    - nodejs
    - postgres
    - nginx-passenger