---
- hosts: vagrant
  user: vagrant
  sudo: yes
  # uncomment for faster provisioning
  # gather_facts: False

  roles:
    - common
    - deploy-user
    - ruby
    - nodejs
    # - nginx-passenger
    # - postgres