---
- hosts: production
  user: root
  sudo: yes
  vars:
    - distro_codename: trusty

  roles:
    - common
    - deploy-user
    - ruby
    - nodejs
    - postgres
    - nginx-passenger
    - unicorn