---
- name: Install PPA for latest Ruby version
  apt_repository: repo=ppa:brightbox/ruby-ng state=present

- name: Install Ruby package
  apt: pkg={{item}} state=latest update_cache=yes
  with_items:
    - ruby2.1
    - ruby2.1-dev